name       : python-parver
version    : 0.2.1
release    : 2
source     :
    - https://github.com/RazerM/parver/archive/0.2.1.tar.gz : 7fcdb486e3c53519a4a70e71a47242ba3c9c8b15804565a1009f338bf5bde43a
license    : MIT
component  : programming.python
summary    : Parse and manipulate version numbers
description: |
    python-parver allows parsing and manipulation of PEP 440 version numbers
builddeps  :
    - python-arpeggio
    - python-attrs
    - python-hypothesis
    - python-pretend
    - python-pytest
    - python-setuptools
    - python-six
rundeps    :
    - python-arpeggio
    - python-attrs
    - python-six
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
