name       : python-parver
version    : 0.1.1
release    : 1
source     :
    - https://github.com/RazerM/parver/archive/0.1.1.tar.gz : b8a43246df0db98f44bceb2c788fb92d1e536cf56cda73f326d7b0b9ecc537f0
license    : MIT
component  : programming.python
summary    : Parse and manipulate version numbers
description: |
    python-parver allows parsing and manipulation of PEP 440 version numbers
builddeps  :
    - python-arpeggio
    - python-attrs
    - python-setuptools
    - python-six
rundeps    :
    - python-arpeggio
    - python-attrs
    - python-six
build      : |
    %python3_setup
install    : |
    %python3_install
